### ISSUE TITLE
(adc2019.py) ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

### ISSUE THREAD

**Issue by ysnt27** [dasadc/adc2019#48]
```
$ python adc2019.py --debug --Q-file ../samples/Q/sample_8_Q.txt --A-file ../samples/A/sample_1_A.txt
False SIZE 72X72
False BLOCK_NUM 2
False 
False BLOCK#1 3X2
True 0,1,0
True +,+,+
True 
False BLOCK#2 3X2
True 0,1,0
True +,+,+
True 
False 
False A1
False SIZE 2X4
True 1,1
True +,+
True +,+
True +,+
True BLOCK#1 @(0,0)
False BLOCK#2 @(1,0)
Traceback (most recent call last):
  File "/home/USER/adc2019/server/adc2019.py", line 1042, in <module>
    main()
  File "/home/USER/adc2019/server/adc2019.py", line 1024, in main
    raise e
  File "/home/USER/adc2019/server/adc2019.py", line 1021, in main
    info = check(args.Q_file, args.A_file)
  File "/home/USER/adc2019/server/adc2019.py", line 998, in check
    return check_data(Q, A[1:])
  File "/home/USER/adc2019/server/adc2019.py", line 699, in check_data
    block_ban_masked = block_ban * np_block[key]
ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 
```

**Comment by ysnt27** [comment]
### この例外が発生する条件

- Qファイルにて記述されているブロックのサイズのほうが
- Aファイルに記述されている盤面サイズよりも、大きいとき

**Comment by ysnt27** [comment]
### エラーを追加: check-QA5: A-SIZE is smaller than Q-BLOCK size

```
$ python adc2019.py --Q-file ../samples/Q/sample_8_Q.txt --A-file ../samples/A/sample_1_A.txt
ADC2021 rule violation
check-QA5: A-SIZE is smaller than Q-BLOCK size
```
